saxix/django-adminactions

adminactions/mass_update.py

Use collections.OrderedDict instead for Django1.7 or higher.
https://docs.djangoproject.com/en/1.8/ref/utils/#django.utils.datastructures.SortedDict

SortedDict has been deprecated since Django 1.7

---

CHANGES
adminactions/__init__.py

The idea is taken from [django docs on outputting large CSV files](https://docs.djangoproject.com/en/1.8/howto/outputting-csv/#streaming-csv-files)
* includes test and documentation
* Stream using HttpResponse for Django <= 1.5.
Even though Django 1.5 supports StreamingHttpResponse,
[ticket #20331](https://code.djangoproject.com/ticket/20331)
prevents admin actions from using it, and the fix django/django@b75a3b0df91579723737403823353861de2ba208 was
included only since Django 1.6

feat(api): allow streaming export to CSV response

---

adminactions/api.py
tests/test_exports.py

While working on streaming export response, I noticed that the xls export is noticeably slower than csv export of same data. While I did not find an easy way to implement streaming xls files, I did find a way to cut response time. It appears that reusing xls styles for given format (as opposed to creating new ones for each cell) shortens the response time by over 40%.
I arrived at figure after running multiple full tox tests (for the supported versions) and comparing the medians of a response that exports ~ 3k rows. And here comes the tricky part: how can we test this time improvement reliably?
On my machine (Retina MBP 2013), the median response time without the fix was 7.54s, and with the fix 4.3s; moreover, with the fix it was always under 5.5s. While we cannot safely hit 5.5 always, I …

fix(api): reuse xls style while iterating over cells

---

adminactions/export.py

This allows providing a dictionary in settings.ADMINACTIONS_CSV_OPTIONS_DEFAULT to customize initial values of the CSV Export form. E.g. to always mark headers by default you would do:
ADMINACTIONS_CSV_OPTIONS_DEFAULT = {"header": True}

feat(export): add initial form values for CSV export

---

src/adminactions/byrows_update.py
src/adminactions/export.py
src/adminactions/graph.py
src/adminactions/mass_update.py
src/adminactions/merge.py
src/adminactions/templates/adminactions/byrows_update.html
src/adminactions/templates/adminactions/charts.html
src/adminactions/templates/adminactions/export_csv.html
src/adminactions/templates/adminactions/export_fixture.html
src/adminactions/templates/adminactions/export_xls.html
src/adminactions/templates/adminactions/mass_update.html
src/adminactions/templates/adminactions/merge.html

See https://docs.djangoproject.com/en/1.9/ref/contrib/admin/#django.contrib.admin.AdminSite.each_context
For example, it allow to  change the admin site_header and site_title variables and have it display correctly on the different admin actions pages.
That is, use the same pattern to display the action name on the different pages and use the action short_description variable.

Add AdminSite.each_context() variables to templates context + "normalize" action display name across interface

---

src/adminactions/merge.py

When we choose to move dependencies, m2m param is not passed. This patch fixes it.

passing m2m param to api.merge in apply step

---

src/adminactions/api.py

If `field.many_to_many` parameter is not defined, `django-adminactions` merge action will crash. This fixes that.

don't crash if field.many_to_many is defined

---

src/adminactions/merge.py
src/adminactions/templates/adminactions/merge_preview.html

Filters and other query string parameters are lost during merge action. This is unpleasant and can even lead to error if the default filter queryset is overridden. This fixes that.
Note: loss of query string parameter can be issue also in other actions. But I don't use them, so I fixed only the merge action.

preserve query string parameters (namely filters) during merge action

---

setup.py

Installation was failing for Python 3.6 because Python 3.6 fell outside the `if/elif` statement where `app` is defined. This is a quick fix for that.

Add Python 3.6 check to setup.py

---

src/adminactions/templatetags/massupdate.py

Before this, a warning is always thrown for `src/adminactions/templatetags/massupdate.py` because it tries to import first the outdated module path. Only if that fails, it tries the next new one.
With this change, the code imports first from new location to then try importing from old location. That ensures old code still works and new code gets no warning.

Avoid RemovedInDjango19Warning from massupdate

---

src/adminactions/static/adminactions/js/merge.js

In the merge action selection, if both sides are the same, the green color on one side doesn't make much sense. If the green color is showed only when there is difference, then user clearly sees on which fields he should decide which side to choose.

merge: don't show green, if both sides are the same

---

src/adminactions/merge.py

Since Django 1.10, required fields adds `required` attribute. It causes, that the `Preview` button does nothing, which is very confusing. If required fields are omitted, it shows standart clean errors.

don't use required attribute -> fix inactive merge button

---

src/adminactions/merge.py

Sometimes the JavaScripts are ordered in such order, that `merge.min.js` is before `jquery.init.js`. In that case the merge action doesn't work, because it has not access to JQuery at load time.
This fixes that, but I don't consider it an ideal solution, because it uses fixed JQuery path, which can interfere with changed path in settings.
Please have a look at this and try  to suggest better solutions.

ensure, that jquery is loaded before merge.min.js

---

src/adminactions/mass_update.py
src/adminactions/templatetags/massupdate.py

There are actually three changes here, the last of which is a tiny bugfix.
1. Instead of using regular form fields, use the fields and widgets as specified in the model form. This automatically takes care of `raw_id_fields` and `autocomplete_fields` so this module doesn't try to render thousands of items with large foreign keys
2. Do the sample values queries only once and only select a reasonably sized sample to prevent killing the system with large tables
3. The `link_fields_values` gives a `ValueError` for me instead of a `TypeError` when handed a single value.

Huge mass update performance fixes for large tables

---

src/adminactions/templatetags/massupdate.py

Trying to split a string (like the key in choices) raises a `ValueError` instead of `TypeError`.

fix a crash with Django model choices

---

src/adminactions/byrows_update.py
tests/test_byrows_update.py

This fix includes #158 as well so it's actually slightly smaller.
The fix is similar, there was a bug with the `readonly_fields` that are assumed to be tuples in all cases.
And instead of loading all foreign key items it uses the same fields as the regular model admin would so it doesn't kill your system when running it on a big database.

By rows bug fix and performance + usability fix

---

src/adminactions/api.py
src/adminactions/byrows_update.py
src/adminactions/forms.py
src/adminactions/merge.py
src/adminactions/utils.py

Hi,
i needed to ignore some fields from update/merging to avoid some security issue and i did this change.
With this setting variable we are able to ignore fields from mass update / per row update:
```
UPDATE_ACTION_IGNORED_FIELDS = {
'app_name': {
'user': ['is_staff', 'is_superuser'],
},
}
```
and also with this variable we are able to ignore merging => and all ignored fields are set to default (if set).
```
MERGE_ACTION_IGNORED_FIELDS = {
'app_name': {
'user': ['is_staff', 'is_superuser'],
},
}
```

allow use ignore_fields to avoid unauthorized merge/update

---

src/adminactions/static/adminactions/js/jqplot/plugins/jqplot.barRenderer.js
src/adminactions/static/adminactions/js/jqplot/plugins/jqplot.pieRenderer.js

There is a small typo in src/adminactions/static/adminactions/js/jqplot/plugins/jqplot.barRenderer.js, src/adminactions/static/adminactions/js/jqplot/plugins/jqplot.pieRenderer.js.
Should read `successive` rather than `succesive`.

docs: Fix simple typo, succesive -> successive

---

src/adminactions/api.py

FieldDoesNotExist has been removed from django.db.fields in Django 3.1 It is now only in django.core.exceptions.
Should address import issue found in: https://github.com/saxix/django-adminactions/issues/166
`django-dynamic-fixtures` has a test dependency that relies on the same exception waiting for this to be merged: https://github.com/paulocheque/django-dynamic-fixture/pull/134

Move FieldDoesNotExist import

---

docs/source/install.rst

* Fixes https://github.com/saxix/django-adminactions/issues/191
* Fixed a typo (wanto to > want to)
* Adjusted line breaks to two between sections
* Example shows different but highly useful defaults
* Link to full settings

Add default config for export to CSV to docs

---

src/adminactions/mass_update.py

If field type is ManyRelatedManager, default function "set" throw error 500
"Direct assignment to the forward side of a many-to-many set is prohibited. Use category.set() instead."
I don't know if it is best way to fix it like my pull request.
Thanks.

fix set if field is ManyRelatedManager

---

src/adminactions/mass_update.py
src/adminactions/static/adminactions/js/jqplot/plugins/jqplot.barRenderer.js
src/adminactions/static/adminactions/js/jqplot/plugins/jqplot.categoryAxisRenderer.js
src/adminactions/static/adminactions/js/jqplot/plugins/jqplot.pieRenderer.js
tests/conftest.py

There are small typos in:
- src/adminactions/mass_update.py
- src/adminactions/static/adminactions/js/jqplot/plugins/jqplot.barRenderer.js
- src/adminactions/static/adminactions/js/jqplot/plugins/jqplot.categoryAxisRenderer.js
- src/adminactions/static/adminactions/js/jqplot/plugins/jqplot.pieRenderer.js
- tests/conftest.py
Fixes:
- Should read `currently` rather than `currenty`.
- Should read `remove` rather than `removee`.
- Should read `labels` rather than `lables`.
- Should read `convenience` rather than `convienence`.
- Should read `accidentally` rather than `accidently`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos
